from telegram.ext import ConversationHandler

(
    LOOP,
    SET_WORD_ATTR, INP_WORD, INP_TRANSLATE, INP_NOTE,
    SET_DICT_ATTR, INP_MAIN_LANGUAGE, INP_TRANSLATE_LANGUAGE, SEL_INTERVAL_LIST,
    INP_SEARCH_VALUE_CH,
    RESET_WORD_ATTR, INP_WORD_CH, INP_TRANSLATE_CH, INP_NOTE_CH,
    INP_SEARCH_VALUE_DEL, CONFIRM_DEL,
    SEL_DICT,
    MESSAGE_TRANSLATE,
) = map(str, range(18))

START_LOOP, CANCEL, ABOUT, SETTINGS, START_REPETITION, ROOT, ACTION = map(str, range(18, 25))

END = ConversationHandler.END

__all__ = [
    "LOOP",
    "SET_WORD_ATTR", "INP_WORD", "INP_TRANSLATE", "INP_NOTE",
    "SET_DICT_ATTR", "INP_MAIN_LANGUAGE", "INP_TRANSLATE_LANGUAGE", "SEL_INTERVAL_LIST",
    "INP_SEARCH_VALUE_CH",
    "RESET_WORD_ATTR", "INP_WORD_CH", "INP_TRANSLATE_CH", "INP_NOTE_CH",
    "INP_SEARCH_VALUE_DEL", "CONFIRM_DEL",
    "SEL_DICT",
    "MESSAGE_TRANSLATE",
    "END",
    "START_LOOP", "CANCEL",
    "ABOUT", "SETTINGS",
    "START_REPETITION",
    "ROOT", "ACTION",
]