from telegram.ext import ConversationHandler

END = ConversationHandler.END

(
    SET_DICT_ATTR, INP_MAIN_LANGUAGE, INP_TRANSLATE_LANGUAGE, SEL_INTERVAL_LIST,
    ADD_WORD, ADD_DICT, SEL_DICT, ABOUT, SETTINGS, START_REPETITION, CONFIRM, SEARCH_WORD, OUT_DOOR,
    CONDITION_ABOUT, CONDITION_SETTINGS, CONFIRM_DICT,
    CANCEL,
    ROOT,
    ACTION,
) = map(str, range(19))
