services:
  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend: 
    build: .
    container_name: backend
    restart: always
    env_file: .env
    depends_on:
      - db

volumes:
  postgres_data: